In [1]:
import pandas as pd

file_path = 'bee-sbv-point.csv'
bee_data = pd.read_csv(file_path, encoding='cp949')

filtered_bee_data = bee_data[bee_data['축종'].isin(['벌-개량종', '벌-재래종'])]
filtered_bee_data

,가축전염병명,농장명,농장소재지,Latitude,Longitude,발생일자,축종,발생두수,진단기관,종식일,...,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,낭충봉아부패병,이동일,경상북도 영양군 수비면 오기리,36.740386,129.198325,2018-12-24 (2018-12-27),벌-재래종,7,경북 북부지소,2019-03-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,낭충봉아부패병,김국도,경상북도 영양군 수비면 죽파리,36.718109,129.246274,2018-12-24 (2018-12-27),벌-재래종,3,경북 북부지소,2019-03-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,낭충봉아부패병,서석하,강원도 인제군 인제읍 가아리,38.145364,128.133598,2018-12-19 (2018-12-21),벌-재래종,4,강원 북부지소,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,낭충봉아부패병,정이분,경상북도 군위군 효령면 거매리,36.153339,128.604167,2018-12-04 (2018-12-26),벌-개량종,20,세균질병과,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,낭충봉아부패병,김정임,경상북도 영덕군 지품면 지품리,36.478507,129.167912,2018-11-23 (2018-11-29),벌-재래종,107,경북 동부지소,2023-10-06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1362,낭충봉아부패병,인천대,인천광역시 연수구 송도동,37.386096,126.638920,2019-02-09 (2019-02-09),벌-재래종,7,인천 보건환경연구원,2019-02-27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1363,낭충봉아부패병,김종순,강원도 인제군 인제읍 가아리,38.145364,128.133598,2019-01-30 (2019-02-01),벌-재래종,2,강원 북부지소,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1364,낭충봉아부패병,'-,경기도 오산시 지곶동,37.176540,127.026306,2019-01-29 (2019-02-08),벌-재래종,1,경기도 동물위생시험소,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1366,낭충봉아부패병,권석렬,경상북도 영양군 수비면 발리리,36.787763,129.203009,2019-01-04 (2019-01-08),벌-재래종,7,경북 북부지소,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1367,낭충봉아부패병,수원시 평생학습관,경기도 수원시 팔달구 우만동,37.284822,127.035245,2019-01-02 (2019-01-04),벌-개량종,3,경기도 동물위생시험소,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
filtered_bee_data = filtered_bee_data[['Latitude', 'Longitude', '축종', '발생두수']]
filtered_bee_data

       Latitude   Longitude     축종  발생두수
0     36.740386  129.198325  벌-재래종     7
1     36.718109  129.246274  벌-재래종     3
2     38.145364  128.133598  벌-재래종     4
4     36.153339  128.604167  벌-개량종    20
5     36.478507  129.167912  벌-재래종   107
...         ...         ...    ...   ...
1362  37.386096  126.638920  벌-재래종     7
1363  38.145364  128.133598  벌-재래종     2
1364  37.176540  127.026306  벌-재래종     1
1366  36.787763  129.203009  벌-재래종     7
1367  37.284822  127.035245  벌-개량종     3

[1319 rows x 4 columns]

In [3]:
output_file_path = 'bee_filtered.csv'
filtered_bee_data.to_csv(output_file_path, index=False)